baseURL = "https://jlian.co"
languageCode = "en-us"
title = "John Lian"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  custom_css = "/css/style.css"
  favicon = "/images/favicon.ico"
  description = "John Lian's personal website"
  facebook = ""
  twitter = "https://twitter.com/jlian"
  instagram = "https://www.instagram.com/__jlian__/"
  youtube = ""
  github = "https://github.com/jlian"
  linkedin = "https://www.linkedin.com/in/jlian1/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  body_classes = "avenir"
  featured_image = "/images/seattle.jpg"
  recent_posts_number = 3